apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: conversao-temperatura
spec:
# replicas: 2
  selector:
    matchLabels: 
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: kaiquen/conversao-temperatura:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: conversao-temperatura
spec: 
  selector:
    app: conversao-temperatura
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30000
  type: NodePort
  


# Pod
# ReplicaSet
# Deployment
# Service